openapi: 3.0.0
info:
  title: Runeterra Lore API
  version: 1.0.0
paths:
  /champions:
    get:
      summary: Get all champions
      responses:
        '200':
          description: Champion list
  /champions/{id}:
    get:
      summary: Get champion detail
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Champion detail
components:
  schemas:
    ChampionSummary:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        title:
          type: string
    ChampionDetail:
      allOf:
        - $ref: '#/components/schemas/ChampionSummary'
        - type: object
          properties:
            region:
              type: string
            bio:
              type: string
